config/routes.rb
require Rails.root.join('lib/build_constraints_regex')

Rails.application.routes.draw do
  # portal home
  root "welcome#index"

  # authorized oauth providers
  authorized_providers = ["github", "google_oauth2"]
  PROVIDER_CONSTRAINTS = { provider: build_contraints_regex(authorized_providers) }

  get "/auth/:provider/callback", to: "users#new_or_edit_oauth", constraints: PROVIDER_CONSTRAINTS

  # google calendar integration
  # get "/calendar/auth/google_oauth2/callback" => "calendars#create"

  scope "/:locale" do
    # authorization routes
    get "/login" => "sessions#login"
    post "/login" => "sessions#create"
    delete "/logout" => "sessions#logout"

    # normal resources
    resources :broadcasts
    resources :guest_lectures, :path => "lectures"
    resources :notes
    resources :users

    # calendars w/ events inside
    resources :calendars do
      post "/request" => "events#request_shift"
      resources :events do
        patch "/approve" => "events#approve"
      end
    end

    # categories w/ categorizables inside
    resources :categories do
      get "/broadcasts" => "categories#broadcasts"
      get "/lectures" => "categories#guest_lectures"
      get "/notes" => "categories#notes"
      get "/users" => "categories#users"
    end
  end
end

app/models/event.rb
require "#{ Rails.root }/lib/gcal_v3_wrapper"

class Event < ActiveRecord::Base
  # Associations ---------------------------------------------------------------
  belongs_to :calendar # calendars_users join table to store viewing permissions?
  belongs_to :guest_lecture
  belongs_to :user
  has_and_belongs_to_many :users

  # Callbacks ------------------------------------------------------------------
  after_create :create_gcal_event
  before_update :move_gcal_event, if: :calendar_id_changed?
  after_update :update_gcal_event
  before_destroy :destroy_gcal_event

  # Validations ----------------------------------------------------------------
  validates_presence_of :title, :start_time, :end_time, :calendar_id
  validates_presence_of :calendar
  validates :google_event_id, length: { maximum: 1024 }, allow_blank: true
  validates :calendar_id, numericality: { only_integer: true }
  validate :start_time_must_be_before_end_time

  # Scopes ---------------------------------------------------------------------
  scope :approved, -> { where(approved: true) }
  scope :pending, -> { where(approved: false) }
  scope :ta, -> { approved.where(ta: true) }
  scope :gl, -> { approved.where(gl: true) }

  scope :in_range, lambda { |date1, date2|
    where("start_time BETWEEN ? AND ?", date1, date2)
  }

  scope :month, lambda { |m = Time.now.month, yyyy = Time.now.year|
    in_range(Time.parse("#{ yyyy }/#{ m }/1"), Time.parse("#{ yyyy }/#{ m + 1 }/1"))
  }

  scope :today, -> { in_range(Time.parse(Date.today.to_s), Time.parse(Date.tomorrow.to_s)) }
  # scope :today, -> { where("? BETWEEN start_time AND end_time", Date.today) }
  # scope :this_month -> { where("start_time BETWEEN ? AND ?", Date.today.at_beginning_of_month, Date.today.at_end_of_month) }
  scope :future, -> { where("start_time > ?", Date.yesterday) }
  scope :chronological, -> { order(:start_time) } # this should happen last, because expensive

  DEFAULT_ADDRESS = "1215 4th Ave #1050, Seattle, WA 98161"

  def approve
    event = event_params
    event['attendees'] = [{ 'email' => user.email }]

    notify = true
    if update_gcal_event(event, notify)
      update_column(:approved, true)
    else
      errors.add(:approved, "oops something went wrong what happen bro") # FIXME: internationalize this error
    end
  end

  private
    def create_gcal_event
      google_id = GCalV3Wrapper::Event.create({
        calendar_id: calendar.google_calendar_id,
        event: event_params
      })

      self.update_column(:google_event_id, google_id)
    end

    def update_gcal_event(event=event_params, notify=false)
      GCalV3Wrapper::Event.update({
        calendar_id: calendar.google_calendar_id,
        event_id: google_event_id,
        sendNotifications: notify,
        event: event
      })
    end

    def destroy_gcal_event
      result = GCalV3Wrapper::Event.destroy({
        calendar_id: calendar.google_calendar_id,
        event_id: google_event_id
      })

      return result
    end

    def move_gcal_event
      changes = self.changes[:calendar_id]
      old_calendar_id = changes[0]
      new_calendar_id = changes[1]

      old_gcal_id = Calendar.find(old_calendar_id).google_calendar_id
      new_gcal_id = Calendar.find(new_calendar_id).google_calendar_id

      result = GCalV3Wrapper::Event.move({
        old_calendar_id: old_gcal_id,
        new_calendar_id: new_gcal_id,
        event_id: self.google_event_id
      })

      return result
    end

    def event_params
      {
        'summary' => title,
        'description' => description,
        'location' => location || DEFAULT_ADDRESS,
        'start' => { 'dateTime' => GCalV3Wrapper.to_iso8601(start_time) },
        'end' => { 'dateTime' => GCalV3Wrapper.to_iso8601(end_time) }
      }
    end

    def start_time_must_be_before_end_time
      unless start_time < end_time
        errors.add(:start_time, "must be before end time") # FIXME: internationalize this error
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :approve, :request]
  before_action :set_calendar
  before_action :require_admin, unless: :user_associated?

  def index
    @events = @calendar.events.chronological
  end

  def show; end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def request_shift
    @event = Event.new(ta_request_params)

    if @event.save
      flash[:success] = I18n.t("success.request_shift")
    else
      flash[:error] = I18n.t("errors.request_shift")
    end

    redirect_to calendar_path(@calendar)
  end

  def approve
    if @event.approve
      flash[:success] = I18n.t(
        "success.event_approved",
        event_title: @event.title,
        date: @event.start_time.strftime("%a, %e %b")
      )
    else
      flash[:error] = I18n.t("errors.event_approved")
    end

    redirect_to calendar_path(@calendar)
  end

  def destroy
    @event.destroy
    redirect_to calendar_path(@calendar)
  end

  private
    def set_calendar
      @calendar = Calendar.find(params[:calendar_id])
    end

    def set_event
      @event = Event.find(params[:event_id] || params[:id])
    end

    def ta_request_params
      form = params.require(:event).permit(:date, :start_time, :end_time)

      event = {}
      event[:title] = "TA: #{ @logged_in_user.name }"
      event[:ta] = true
      event[:approved] = false
      event[:user_id] = @logged_in_user.id
      event[:calendar_id] = @calendar.id
      event[:start_time] = Time.parse("#{ form[:date] } #{ form[:start_time] }")
      event[:end_time] = Time.parse("#{ form[:date] } #{ form[:end_time] }")
      event[:admin_only] = false

      return event
    end

    def event_params
      params.require(:event).permit(
        :title,
        :description,
        :location,
        :start_time,
        :end_time,
        :calendar_id,
        :google_event_id,
        :guest_lecture_id,
        :admin_only#,
        # :category_ids => [],
        # :categories_attributes => [:id, :name]
      )
    end

    def user_associated?
      return @calendar.users.include? @logged_in_user
    end
end

app/views/events/_form.html.erb
<%= form_for [@calendar, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t("attributes.title") %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label t("attributes.description") %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label t("attributes.location") %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label t("attributes.start_time") %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label t("attributes.end_time") %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label t("attributes.google_event_id") %><br>
    <%= f.text_area :google_event_id, width: 500 %>
  </div>
  <div class="field">
    <%= f.label t("attributes.guest_lecture_id") %><br>
    <%= f.text_area :guest_lecture_id, width: 500 %>
  </div>
  <div class="field">
    <label>
    <%= t("attributes.calendar_id") %><br>
    <%= collection_select(:event, :calendar_id, Calendar.all, :id, :name) %>
    </label>
    <!-- <%= f.number_field :calendar_id, value: @calendar.id %> -->
  </div>
  <div class="field">
    <%= f.label t("attributes.admin_only") %><br>
    <%= f.check_box :admin_only %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t("headings.editing", model_name: t("resources.event")) %></h1>

<%= render 'form' %>

<%= link_to t("links.resources.show"), @event %> |
<%= link_to t("links.back"), calendar_events_path(@calendar) %>

app/views/events/index.html.erb
<section class="col-md-10 col-md-offset-1">
  <h1>
    <%= t("headings.all", plural_model_name: t("resources.event").pluralize) %>
    <small><%= link_to t("links.resources.create", model_name: t("resources.event")), new_calendar_event_path %></small>
  </h1>

  <div class="row">
  <% @events.each_with_index do |event, index| %>
    <% if index % 3 == 0 %></div><div class="row"><% end %>
    <div class="item col-sm-4 col-xs-12">
      <div class="action-links col-sm-8 col-sm-offset-2 col-xs-12">
        <h4><%= t("resources.actions") %></h4>
        <%= link_to t("links.resources.show"), calendar_event_path(@calendar, event) %>
        <%= link_to t("links.resources.edit"), edit_calendar_event_path(@calendar, event) %>
        <%= link_to t("links.resources.delete"), calendar_event_path(@calendar, event), method: :delete, data: { confirm: t("confirmations.delete") } %>
      </div>
      <div class="attributes">
        <div class="attribute-name col-xs-12"><%= t("attributes.title") %></div>
        <div class="attribute-value col-xs-12"><%= link_to event.title, calendar_event_path(@calendar, event) %></div>
      </div>
      <div class="attributes">
        <div class="attribute-name col-xs-12"><%= t("attributes.start_time") %></div>
        <div class="attribute-value col-xs-12"><%= event.start_time.strftime("%a, %b %d, %Y") %></div>
      </div>
    </div>
  <% end %>
  </div>
</section>

app/views/events/new.html.erb
<h1><%= t("headings.create", model_name: t("resources.event")) %></h1>

<%= render 'form' %>

<%= link_to t("links.back"), calendar_events_path(@calendar) %>

app/views/events/show.html.erb
<p>
  <strong><%= t("attributes.title") %></strong>
  <%= @event.title %>
</p>

<p>
  <strong><%= t("attributes.description") %></strong>
  <%= @event.description %>
</p>

<p>
  <strong><%= t("attributes.location") %></strong>
  <%= @event.location %>
</p>

<p>
  <strong><%= t("attributes.start_time") %></strong>
  <%= @event.start_time %>
</p>

<p>
  <strong><%= t("attributes.end_time") %></strong>
  <%= @event.end_time %>
</p>

<p>
  <strong><%= t("attributes.google_event_id") %></strong>
  <%= @event.google_event_id %>
</p>

<p>
  <strong><%= t("attributes.guest_lecture_id") %></strong>
  <%= @event.guest_lecture_id || t("attributes.empty") %>
</p>

<p>
  <strong><%= t("attributes.calendar_id") %></strong>
  <%= @event.calendar_id || t("attributes.empty") %>
</p>

<p>
  <strong><%= t("attributes.admin_only") %></strong>
  <%= @event.admin_only %>
</p>

<%= link_to t("links.resources.edit"), edit_calendar_event_path(@calendar, @event) %> |
<%= link_to t("links.back"), calendar_events_path(@calendar) %>