config/routes.rb
require Rails.root.join('lib/build_constraints_regex')

Rails.application.routes.draw do
  # portal home
  root "welcome#index"

  # authorized oauth providers
  authorized_providers = ["github", "google_oauth2"]
  PROVIDER_CONSTRAINTS = { provider: build_contraints_regex(authorized_providers) }

  get "/auth/:provider/callback", to: "users#new_or_edit_oauth", constraints: PROVIDER_CONSTRAINTS

  # google calendar integration
  # get "/calendar/auth/google_oauth2/callback" => "calendars#create"

  scope "/:locale" do
    # authorization routes
    get "/login" => "sessions#login"
    post "/login" => "sessions#create"
    delete "/logout" => "sessions#logout"

    # normal resources
    resources :broadcasts
    resources :guest_lectures, :path => "lectures"
    resources :notes
    resources :users

    # calendars w/ events inside
    resources :calendars do
      post "/request" => "events#request_shift"
      resources :events do
        patch "/approve" => "events#approve"
      end
    end

    # categories w/ categorizables inside
    resources :categories do
      get "/broadcasts" => "categories#broadcasts"
      get "/lectures" => "categories#guest_lectures"
      get "/notes" => "categories#notes"
      get "/users" => "categories#users"
    end
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  # Associations ---------------------------------------------------------------
  has_and_belongs_to_many :users
  has_and_belongs_to_many :students, association_foreign_key: "user_id"
  has_and_belongs_to_many :volunteers, association_foreign_key: "user_id"
  has_and_belongs_to_many :admin, association_foreign_key: "user_id"
  has_many :events
  has_many :special_conditions

  # Validations ----------------------------------------------------------------
  validates_presence_of :name, :google_calendar_id

  # Scopes ---------------------------------------------------------------------
  # scope :rules, lambda { special_conditions.future }
  # scope :ta_events, lambda { events.ta.future }

  def rules
    special_conditions#.future
  end

  def ta_events
    events.ta#.future
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show]
  before_action :require_admin, unless: :user_associated_and_allowed_action?


  def index
    if @admin
      @calendars = Calendar.all
    else
      @calendars = @logged_in_user.calendars
    end
  end

  def show
    @events = @calendar.ta_events
    @pending_events = @calendar.events.pending.limit(10).chronological
    @events = @events + @pending_events
    @students = @calendar.students
    @volunteers = @calendar.volunteers if @admin
    @event = Event.new
  end

  private

    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    def user_associated?
      if params[:action] == "index"
        return @logged_in_user.calendars.count > 0
      elsif params[:action] == "show"
        return @calendar.users.include? @logged_in_user
      end
    end

    def user_associated_and_allowed_action?
      allowed_actions = ["index", "show"]
      return user_associated? if allowed_actions.include? params[:action]
    end
end

app/views/calendars/_events.html.erb
<div class="panel panel-default">
  <div class="panel-heading collapsed" role="tab" id="heading-notifications"
    role="button" href="#collapse-notifications"
    data-toggle="collapse" data-parent="#accordion"
    aria-expanded="false" aria-controls="collapse-notifications">
      <h1 class="panel-title">
        <%= t("headings.notifications.event") %>
        <span class="badge"><%= events.count %></span>
      </h1>
  </div>

  <div id="collapse-notifications" class="panel-collapse collapse"
    role="tabpanel" aria-labelledby="heading-notifications">

    <section id="event-notifications" class="panel-body">

      <% if events.nil? || events.empty? %>

        <div class="well"><%= t("notifications.no_events") %></div>

      <% else %>

        <% events.each_with_index do |event, index| %>
          <div class="item col-xs-12">

            <div class="action-links col-xs-12">
              <%= event.start_time.strftime("%a, %b %e") %>
            </div>

            <div class="col-xs-12">
              <%= event.start_time.strftime("%l:%M %p") %> -
              <%= event.end_time.strftime("%l:%M %p") %><br />
              <%= link_to event.title, user_path(event.user) %><br />

              <%= link_to t("actions.reject"),
                calendar_event_path(event.calendar_id, event),
                method: "delete",
                data: { confirm: t("actions.confirmations.delete") }
              %>

              <i class="space fa fa-bolt"></i>

              <%= link_to t("actions.approve"),
                calendar_event_approve_path(event.calendar_id, event),
                method: "patch"
              %>
            </div>

          </div>

        <% end %>

      <% end %>

    </section>

  </div>
</div>

app/views/calendars/_new_admin_event.html.erb
<div class="panel panel-default">
  <div class="panel-heading collapsed" role="tab" id="heading-event"
    role="button" href="#collapse-event"
    data-toggle="collapse" data-parent="#accordion"
    aria-expanded="false" aria-controls="collapse-event">
      <h1 class="panel-title"><%= t("forms.request_shift") %></h1>
  </div>

  <div id="collapse-event" class="panel-collapse collapse"
    role="tabpanel" aria-labelledby="heading-event">

    <section class="panel-body">

      <%= form_for [@calendar, @event], url: calendar_events_path(@calendar) do |f| %>
        <% if @event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
            <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.hidden_field :title, :value => "TA: #{ @logged_in_user.name }" %>
        <%= f.hidden_field :user_id, value: @logged_in_user.id %>
        <%= f.hidden_field :calendar_id, value: @calendar.id %>

        <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
            <label>Date
            <div class='datepicker input-group date'>
                <input type='text' name="event[date]" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
            </label>
        </div>

        <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
            <%= f.label t("attributes.start_time") %>
            <div class='timepicker-start input-group date'>
                <input type='text' name="event[start_time]" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
        </div>


        <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
            <%= f.label t("attributes.end_time") %><br>
            <div class='timepicker-end input-group date'>
                <input type='text' name="event[end_time]" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
        </div>

        <div class="actions col-xs-12">
          <%= f.submit t("forms.request_shift") %>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/calendars/_new_ta_event.html.erb
<div class="panel panel-default">
  <div class="panel-heading collapsed" role="tab" id="heading-event"
    role="button" href="#collapse-event"
    data-toggle="collapse" data-parent="#accordion"
    aria-expanded="true" aria-controls="collapse-event">
      <h1 class="panel-title"><%= t("forms.request_shift") %></h1>
  </div>

  <div id="collapse-event" class="panel-collapse collapse in"
    role="tabpanel" aria-labelledby="heading-event">

    <section class="panel-body">

      <%= form_for [@calendar, @event], url: calendar_request_path(@calendar) do |f| %>
        <% if @event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
            <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.hidden_field :title, :value => "TA: #{ @logged_in_user.name }" %>
        <%= f.hidden_field :user_id, value: @logged_in_user.id %>
        <%= f.hidden_field :calendar_id, value: @calendar.id %>

        <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
            <label>Date
            <div class='datepicker input-group date'>
                <input type='text' name="event[date]" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
            </label>
        </div>

        <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
            <%= f.label t("attributes.start_time") %>
            <div class='timepicker-start input-group date'>
                <input type='text' name="event[start_time]" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
        </div>


        <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
            <%= f.label t("attributes.end_time") %><br>
            <div class='timepicker-end input-group date'>
                <input type='text' name="event[end_time]" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
        </div>

        <div class="actions col-xs-12">
          <%= f.submit t("forms.request_shift") %>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/calendars/_pending_events.html.erb
<div class="panel panel-default">
  <div class="panel-heading collapsed" role="tab" id="heading-notifications"
    role="button" href="#collapse-notifications"
    data-toggle="collapse" data-parent="#accordion"
    aria-expanded="<%= events.count > 0 %>" aria-controls="collapse-notifications">
      <h1 class="panel-title">
        <%= t("headings.notifications.event") %>
        <span class="badge"><%= events.count %></span>
      </h1>
  </div>

  <div id="collapse-notifications" class="panel-collapse collapse<%= ' in' if events.count > 0 %>"
    role="tabpanel" aria-labelledby="heading-notifications">

    <section id="event-notifications" class="panel-body">

      <% if events.nil? || events.empty? %>

        <div class="well"><%= t("notifications.no_events") %></div>

      <% else %>

        <% events.each_with_index do |event, index| %>
          <div class="item col-md-6 col-xs-12">

            <div class="action-links col-xs-12">
              <%= event.start_time.strftime("%a, %b %e") %>
            </div>

            <div class="col-xs-12">
              <%= event.start_time.strftime("%l:%M %p") %> -
              <%= event.end_time.strftime("%l:%M %p") %><br />
              <%= link_to event.title, user_path(event.user) %><br />

              <%= link_to t("actions.reject"),
                calendar_event_path(event.calendar_id, event),
                method: "delete",
                data: { confirm: t("actions.confirmations.delete") }
              %>

              <i class="space fa fa-bolt"></i>

              <%= link_to t("actions.approve"),
                calendar_event_approve_path(event.calendar_id, event),
                method: "patch"
              %>
            </div>

          </div>

        <% end %>

      <% end %>

    </section>

  </div>
</div>

app/views/calendars/_users.html.erb
<div class="panel panel-default">
  <div class="panel-heading collapsed" role="tab" id="heading-<%= type %>"
    href="#collapse-<%= type %>" data-toggle="collapse" data-parent="#accordion"
    aria-expanded="false" aria-controls="collapse-<%= type %>" role="button">

    <h1 class="panel-title">
      <%= t("headings.all", plural_model_name: t("resources.users.#{ type }")) %>
    </h1>

  </div>

  <div id="collapse-<%= type %>" class="panel-collapse collapse"
    role="tabpanel" aria-labelledby="heading-<%= type %>">

    <section class="panel-body">

      <div class="row">
        <% users.each_with_index do |user, index| %>
          <% if index % 3 == 0 %></div><div class="row"><% end %>

          <div class="item col-sm-4 col-xs-12">
            <div class="col-xs-12"><%= link_to user.name, user_path(user) %></div>
            
            <% if user.github %>
                <div class="col-xs-12">
                  <i class="fa fa-github"></i>
                  <%= link_to user.github, "https://github.com/#{ user.github }" %>
                </div>
            <% end %>
          </div>

        <% end %>
      </div>

    </section>

  </div>
</div>

app/views/calendars/index.html.erb
<section class="col-md-10 col-md-offset-1">
  <h1>
    <%= t("headings.all", plural_model_name: t("resources.calendar").pluralize) %>
    <small><%= link_to t("links.resources.create", model_name: t("resources.calendar")), new_calendar_path %></small>
  </h1>

  <div class="row">
  <% @calendars.each_with_index do |calendar, index| %>
    <% if index % 3 == 0 %></div><div class="row"><% end %>
    <div class="item col-sm-4 col-xs-12">
      <div class="action-links col-sm-8 col-sm-offset-2 col-xs-12">
        <h4><%= link_to t("resources.calendar_with_name", name: calendar.name), calendar %></h4>
      </div>
      <div class="col-sm-8 col-sm-offset-2 col-xs-12">
        <%= link_to t("links.resources.show"), calendar %>
        <%= link_to t("links.resources.edit"), edit_calendar_path(calendar) %>
        <%= link_to t("links.resources.delete"), calendar, method: :delete, data: { confirm: t("confirmations.delete") } %>
      </div>
    </div>
  <% end %>
  </div>
</section>

app/views/calendars/show.html.erb
<section class="col-md-12">
  <div class="row">
    <h1 class="col-sm-6 col-xs-12">
      <%= t("resources.calendar_with_name", name: @calendar.name) %>
    </h1>
  </div>

  <div class="calendar col-sm-6 col-xs-12">

    <%= month_calendar events: @events, pendings: @pending_events do |date, events, pendings| %>
      <%= date.day %>

      <% events.each do |event| %>
        <% if event.approved %>
          <div class="event"></div>
        <% else %>
          <div class="pending"></div>
        <% end %>
      <% end %>
    <% end %>

    <div id="legend" class="row"></div>

    <p class="visible-xs"></p>
    <p class="delete-after-presentation"></p>
    <p class="delete-after-presentation"></p>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="panel-group" id="accordion" role="tablist">
      <% if @calendar.curriculum_href %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title">
                <% if @calendar.curriculum_href.include? "github" %>
                  <i class="fa fa-github"></i>
                <% elsif @calendar.curriculum_href.include? "google" %>
                  <i class="fa fa-google-plus"></i>
                <% end %>
                <%= link_to t("attributes.curriculum_href"), @calendar.curriculum_href %>
              </h1>
            </div>
          </div>
      <% end %>


      <% if @admin %>
        <%= render partial: 'new_admin_event' %>
      <% else %>
        <%= render partial: 'new_ta_event' %>
      <% end %>

      <% if @admin %>
        <%= render partial: 'pending_events', locals: { events: @pending_events } %>
        <%= render partial: 'users', locals: { users: @volunteers, type: "volunteer" } %>
      <% end %>

      <%= render partial: 'users', locals: { users: @students, type: "student" } %>
    </div>
  </div>
</section>