config/routes.rb
require Rails.root.join('lib/build_constraints_regex')

Rails.application.routes.draw do
  # portal home
  root "welcome#index"

  # authorized oauth providers
  authorized_providers = ["github", "google_oauth2"]
  PROVIDER_CONSTRAINTS = { provider: build_contraints_regex(authorized_providers) }

  get "/auth/:provider/callback", to: "users#new_or_edit_oauth", constraints: PROVIDER_CONSTRAINTS

  # google calendar integration
  # get "/calendar/auth/google_oauth2/callback" => "calendars#create"

  scope "/:locale" do
    # authorization routes
    get "/login" => "sessions#login"
    post "/login" => "sessions#create"
    delete "/logout" => "sessions#logout"

    # normal resources
    resources :broadcasts
    resources :guest_lectures, :path => "lectures"
    resources :notes
    resources :users

    # calendars w/ events inside
    resources :calendars do
      post "/request" => "events#request_shift"
      resources :events do
        patch "/approve" => "events#approve"
      end
    end

    # categories w/ categorizables inside
    resources :categories do
      get "/broadcasts" => "categories#broadcasts"
      get "/lectures" => "categories#guest_lectures"
      get "/notes" => "categories#notes"
      get "/users" => "categories#users"
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  # Validations ----------------------------------------------------------------
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # Associations ---------------------------------------------------------------
  belongs_to :categorizable, polymorphic: true
  has_many :category_joins
  has_many :broadcasts, through: :category_joins, source: :categorizable,
    source_type: 'Broadcast'
  has_many :lectures, through: :category_joins, source: :categorizable,
    source_type: 'GuestLecture'
  has_many :notes, through: :category_joins, source: :categorizable,
    source_type: 'Note'
  has_many :users, through: :category_joins, source: :categorizable,
    source_type: 'User'

  # Scopes ---------------------------------------------------------------------
  scope :pending, -> { where(approved: false) }
  scope :alphabetized, -> { order(:name) }
  scope :not_admin, -> { where(admin_only: false) }
  scope :admin, -> { where(admin_only: true) }
  scope :visible, -> { where(hidden: false).where(approved: true).alphabetized }
  scope :tags, -> { where(user_related: true) }
  scope :topics, -> { where(topic_related: true) }
  scope :any_user, -> { visible.not_admin }
  scope :any_user_tags, -> { any_user.tags }
  scope :any_user_topics, -> { any_user.topics }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.alphabetized
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :color, :admin_only, :approved)
    end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t("attributes.name") %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label t("attributes.admin_only") %><br>
    <%= f.check_box :admin_only %>
  </div>
  <div class="field">
    <%= f.label t("attributes.approved") %><br>
    <%= f.check_box :approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t("headings.editing", model_name: t("resources.category")) %></h1>

<%= render 'form' %>

<%= link_to t("links.resources.show"), @category %> |
<%= link_to t("links.back"), categories_path %>

app/views/categories/index.html.erb
<section class="col-md-10 col-md-offset-1">
  <h1>
    <%= t("headings.all", plural_model_name: t("resources.category").pluralize) %>
    <small><%= link_to t("links.resources.create", model_name: t("resources.category")), new_category_path %></small>
  </h1>

  <div class="row">
  <% @categories.each_with_index do |category, index| %>
    <% if index % 3 == 0 %></div><div class="row"><% end %>
    <div class="item col-sm-4 col-xs-12">
      <div class="row">
        <div class="action-links col-sm-8 col-sm-offset-2 col-xs-12">
          <h4><%= category.name %></h4>
          <%= link_to t("links.resources.show"), category %>
          <%= link_to t("links.resources.edit"), edit_category_path(category) %>
          <%= link_to t("links.resources.delete"), category, method: :delete, data: { confirm: t("confirmations.delete") } %>
        </div>
      </div>
      <div class="category">
        <% ["hidden", "admin_only", "user_related", "topic_related"].each do |attr| %>
          <% if category[attr] %>
            <span class="badge"><%= t("attributes.#{ attr }") %></span>
          <% end %>
        <% end %>
        <%= category.description %>
      </div>
    </div>
  <% end %>
  </div>
</section>

app/views/categories/new.html.erb
<h1><%= t("headings.create", model_name: t("resources.category")) %></h1>

<%= render 'form' %>

<%= link_to t("links.back"), categories_path %>

app/views/categories/show.html.erb
<p>
  <strong><%= t("attributes.name") %></strong>
  <%= @category.name %>
</p>

<p>
  <strong><%= t("attributes.admin_only") %></strong>
  <%= @category.admin_only %>
</p>

<p>
  <strong><%= t("attributes.approved") %></strong>
  <%= @category.approved %>
</p>

<p>
  <strong><%= t("attributes.hidden") %></strong>
  <%= @category.hidden %>
</p>

<h3>
  Things belonging to this category<br />
  <small>Total: <%= @category.category_joins.count %></small>
</h3>
<% if @category.broadcasts.any? %>
  <ul>Broadcasts (Total: <%= @category.broadcasts.count %>)
  <% @category.broadcasts.each do |thing| %>
    <li><%= link_to thing.title, thing %></li>
  <% end %>
  </ul>
<% end %>

<% if @category.notes.any? %>
  <ul>Notes (Total: <%= @category.notes.count %>)
  <% @category.notes.each do |thing| %>
    <li><%= link_to thing.note, thing %></li>
  <% end %>
  </ul>
<% end %>

<% if @category.lectures.any? %>
  <ul>Guest Lectures (Total: <%= @category.lectures.count %>)
  <% @category.lectures.each do |thing| %>
    <li><%= link_to thing.title, thing %></li>
  <% end %>
  </ul>
<% end %>

<% if @category.users.any? %>
  <ul>Users (Total: <%= @category.users.count %>)
  <% @category.users.each do |thing| %>
    <li><%= link_to thing.name, user_path(thing) %></li>
  <% end %>
  </ul>
<% end %>

<%= link_to t("links.resources.edit"), edit_category_path(@category) %> |
<%= link_to t("links.back"), categories_path %>