config/routes.rb
require Rails.root.join('lib/build_constraints_regex')

Rails.application.routes.draw do
  # portal home
  root "welcome#index"

  # authorized oauth providers
  authorized_providers = ["github", "google_oauth2"]
  PROVIDER_CONSTRAINTS = { provider: build_contraints_regex(authorized_providers) }

  get "/auth/:provider/callback", to: "users#new_or_edit_oauth", constraints: PROVIDER_CONSTRAINTS

  # google calendar integration
  # get "/calendar/auth/google_oauth2/callback" => "calendars#create"

  scope "/:locale" do
    # authorization routes
    get "/login" => "sessions#login"
    post "/login" => "sessions#create"
    delete "/logout" => "sessions#logout"

    # normal resources
    resources :broadcasts
    resources :guest_lectures, :path => "lectures"
    resources :notes
    resources :users

    # calendars w/ events inside
    resources :calendars do
      post "/request" => "events#request_shift"
      resources :events do
        patch "/approve" => "events#approve"
      end
    end

    # categories w/ categorizables inside
    resources :categories do
      get "/broadcasts" => "categories#broadcasts"
      get "/lectures" => "categories#guest_lectures"
      get "/notes" => "categories#notes"
      get "/users" => "categories#users"
    end
  end
end

app/views/layouts/application.html.haml
%html
  %head
    %title= t('site.name') + t('site.separator') + t('site.subtitle')
    %meta { name: 'description', content: 'site.description'}
    %meta { name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag '/images/favicon.ico'

  %body
    .container-fluid
      %nav.nav.navbar.navbar-default.navbar-fixed-top
        %ul.nav.navbar-nav
          %li= link_to t('links.home'), root_path

          = if @admin
            / begin admin links
            %li= link_to t('links.admin.calendar'), calendars_path
            %li= link_to t('links.admin.broadcoast'), broadcasts_path
            %li= link_to t('links.admin.category'), categories_path
            %li= link_to t('links.admin.guest_lecture'), guest_lectures_path
            %li= link_to t("links.admin.note"), notes_path
            %li= link_to t("links.admin.user"), users_path
            / end admin links

          = if (@logged_in_user && !@admin)
            / begin logged in user links %>
            -# %li= link_to t("links.guest_lecture"), guest_lectures_path
            %li= link_to t("links.calendar"), calendars_path
            %li= link_to t("links.profile"), user_path(@logged_in_user)
            %li= link_to t("links.settings"), edit_user_path(@logged_in_user)
            / end logged in user links

        %ul.nav.navbar-nav.navbar-right
          = if (@logged_in_user)
            %li= link_to t("links.logout"), logout_path, method: :delete

          = if (!@logged_in_user)
            %li= link_to t("links.login"), login_path

    #spacer

    = if @available_broadcast
      #broadcast.panel.panel-default
        .panel-heading
          %h3.panel-title= @available_broadcast[:title]

        .panel-body
          = @available_broadcast[:description]
          = link_to "https://twitter.com/intent/tweet?text=#{ @available_broadcast[:title] }#{ t("site.separator") }#{ @available_broadcast[:description] }", id: "twitter" do
            %i.fa.fa-twitter
            = t("actions.tweet")

    = if (flash[:error] || flash[:success])
      #flash.well.well-sm
        = if flash[:error]
          = flash[:error]

        = if flash[:success]
          = flash[:success]

    %main
      = yield